version: '3'
services:
  nginx:
    container_name: nginx2
    image: nginx
    ports:
    - 10080:80
    volumes:
    - ./server:/src
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  php:
    container_name: php2
    build: .
    volumes:
    - ./server:/src
    working_dir: /src/sample

  mysql:
    container_name: mysql2
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 23306:3306